### PR TITLE
Make label-warning more easily distinguishable from label-danger

### LINKED ISSUE #43: Blog Post Count Labels Are Indistinguishable in Color
I can't tell the different between the colors for the different blog post counts anymore. Here's an example that [shows this issue](http://bizlegfoss-ritigm.rhcloud.com/participants/)

### PR DESCRIPTION
**Pull request by ryansb**
sample

Resolves #43

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
lgtm :+1:

**Comment by liam-middlebrook** [comment]
I also think that the `label-success` color should be changed.

**Comment by mellolikejello** [comment]
Shouldn't the changes be in site.css? I thought we weren't supposed to make changes to the material bootstrap defaults?

The color looks good though :+1:

**Comment by ryansb** [comment]
Wellll...that'd require I write CSS instead of just using `sed`. I guess I'll fix it correctly then.

**Comment by mellolikejello** [comment]
:+1: 

@liam-middlebrook what color do you think `label-success` should be? a lighter shade of green?

**Comment by liam-middlebrook** [comment]
Yeah a lighter shade would work nice!

**Comment by ryansb** [comment]
Tried lighter green: clashes horribly. 

If you can find a shade you like, patches are welcome.

**Pull request merged**
