### PR TITLE
Adding workflow diagram

### PR DESCRIPTION
**Pull request by ritjoe**
trying to make the pep8 test in TravisCI happy, even though I thought this was msoucy's code already merged?

### CODE REVIEW

**Comment by ritjoe** [comment]
Finally.

**Comment by ryansb** [comment]
You should really try running the tests locally with `tox`, then you don't have to show us how much pep-bowing was required. :100: 

```
$ pip install tox
$ tox
```

For discussion reference, here's the graph embedded because github, presumably for "reasons" doesn't display SVGs. 

ofcourse-workflow

Is the box the instructor computer? Labels would help (on what an arrow means, on what the box is, etc). I think it'd be helpful to label arrows like "fork," "pull request," and "git-deploy" to indicate the different relationships.

**Comment by liam-middlebrook** [comment]
Could you rebase away your PEP8 related changes? Aside from the fact that they are now fixed, it doesn't make sense to include those in with this workflow diagram.

**Comment by ritjoe** [comment]
Yeah, that's what I thought.

I have *no* idea why code I didn't touch at all in any of this, and that
didn't change while I was doing any of this work, should start causing any
trouble.



On Tue, Feb 02, 2016 at 10:08:14AM -0800, Liam Middlebrook wrote:
> Could you rebase away your PEP8 related changes? Aside from the fact that they
> are now fixed, it doesn't make sense to include those in with this workflow
> diagram.
> 
> —
> Reply to this email directly or view it on GitHub.*
> 

-- 
-- 
Joe   On ceding power to tech companies: http://xkcd.com/1118/
man screen | grep -A2 weird
  A weird imagination is most useful to gain full advantage of
  all the features.

**Comment by ritjoe** [comment]
Which is to say, if you can explain to me why PEP8 test was blocking my pull
request over errors in calendar code that was not part of my pull request and
that was, as best I can tell, submitted some time ago by soucy and accepted
into the repo, then maybe I'll have some idea as to why this happened and
what the next appropriate move might be.

In other words, I didn't do so I don't know how to fix it.  If you think you
do, then, as they say, patches welcomed.

-- 
Joe

On Tue, Feb 02, 2016 at 06:49:08PM +0000, D. Joe wrote:
> 
> Yeah, that's what I thought.
> 
> I have *no* idea why code I didn't touch at all in any of this, and that
> didn't change while I was doing any of this work, should start causing any
> trouble.
> 
> 
> 
> On Tue, Feb 02, 2016 at 10:08:14AM -0800, Liam Middlebrook wrote:
> > Could you rebase away your PEP8 related changes? Aside from the fact that they
> > are now fixed, it doesn't make sense to include those in with this workflow
> > diagram.
> > 
> > —
> > Reply to this email directly or view it on GitHub.*
> > 
> 
> -- 
> -- 
> Joe   On ceding power to tech companies: http://xkcd.com/1118/
> man screen | grep -A2 weird
>   A weird imagination is most useful to gain full advantage of
>   all the features.

-- 
-- 
Joe   On ceding power to tech companies: http://xkcd.com/1118/
man screen | grep -A2 weird
  A weird imagination is most useful to gain full advantage of
  all the features.

**Comment by ryansb** [comment]
Fixed & now available on `develop`

**Comment by msoucy** [comment]
Sorry about this. Strange that it wasn't caught sooner, my apologies.

**Pull request closed without merging**
