### PR TITLE
Let's NOT cause a nice attack vector...

### PR DESCRIPTION
**Pull request by msoucy**

### CODE REVIEW

**Comment by liam-middlebrook** [comment]
(y)

**Comment by liam-middlebrook** [comment]
Are there any other places in the codebase where this could be changed?

**Comment by msoucy** [comment]
Not anymore.

**Comment by liam-middlebrook** [comment]
lgtm :+1:

**Comment by msoucy** [comment]
@ryansb so, this is a security issue that should be evaluated (and preferably merged) right away.

@liam-middlebrook that first commit was over SSH from my phone at a PyCon talk when I realized that it was an issue...hence only one fixed location.

**Comment by ryansb** [comment]
I'll look this over, but it isn't urgent because we aren't loading arbitrary yaml, so it isn't an attack vector of consequence.

**Comment by msoucy** [comment]
All it takes is one unobservant, or tired, or distracted professor, with the right creative student...

**Comment by liam-middlebrook** [comment]
@msoucy maybe you should pen-test :stuck_out_tongue_winking_eye:

**Comment by ryansb** [comment]
Can you link to the CVE for why we need safe_load? I really feel it doesn't affect this use case, since it's an issue with untrusted data, not trusted content

**Comment by liam-middlebrook** [comment]
What's the status on this? @msoucy, @ryansb

**Comment by msoucy** [comment]
The status is "What's the status on this @ryansb?"

**Pull request merged**
