### PR TITLE
Material design update

### PR DESCRIPTION
**Pull request by mellolikejello**
Is this the best way to get a code review in? Let me know if there is a better way

### CODE REVIEW

**Comment by ryansb** [comment]
Do you have a migration plan for existing sites?

**Comment by mellolikejello** [comment]
Not yet, I can work on that next

**Comment by ryansb** [comment]
Yeah, what I'm most worried about is that existing sites may have some modified templates and end up with a weird mix of themes.

**Comment by ryansb** [comment]
Discussed with @decause, we'll just do a non-destructive sync of the templates to the existing sites. I'll add an `ofcourse` command to handle it. 

Once the sync is done, the profs can use `git add -p` and accept only the changes they like.

**Comment by ryansb** [comment]
@mellolikejello This is great, I just whipped up the `sync` command and did a (test) migration of the HFOSS site. You can pull down the latest `develop` to try it yourself. :)

**Comment by ryansb** [comment]
Oh, I forgot to ask: is there an easy way for you to detect CSS and such that isn't being used anymore?

**Comment by mellolikejello** [comment]
awesome!

**Comment by mellolikejello** [comment]
I found a firefox plugin to find unused CSS https://addons.mozilla.org/en-us/firefox/addon/dust-me-selectors/ . There were a few others, but I wasn't sure how they'd work with ofcourse.

**Comment by mellolikejello** [comment]
There were just a few unused selectors in site.css. I can remove them

**Pull request merged**
